import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Chapters 1 (Foundations) and 4 (Tech Stack) use manual grouping
 * so the sidebar doesn't become a long scroll. Other chapters use
 * autogeneration driven by each chapter's _category_.json + per-page
 * sidebar_position.
 *
 * Chapter 2 (Roadmap) also uses autogenerate at the chapter root,
 * which picks up each Part's _category_.json under subdirectories.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'model-snapshot',

    // ─────────────────────────────────────────────────────────────
    // Part A · Fundamentals — how LLMs work, and how to learn them
    // ─────────────────────────────────────────────────────────────

    // Chapter 1 — Foundations, grouped into 4 sub-categories + checkpoint
    {
      type: 'category',
      label: '1. Foundations',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'foundations/foundational-concepts'},
      items: [
        'foundations/programming-basics',
        {
          type: 'category',
          label: 'The model',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'The model',
            description:
              'How an LLM actually works under the hood — tokens, embeddings, the transformer, and inference.',
            slug: '/foundations/model',
          },
          items: [
            'foundations/tokens',
            'foundations/tokenizers',
            'foundations/embeddings',
            'foundations/neural-networks',
            'foundations/transformer',
            'foundations/training-vs-inference',
            'foundations/quantization',
            'foundations/reasoning-models',
            'foundations/model-families',
          ],
        },
        {
          type: 'category',
          label: 'Using the API',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Using the API',
            description:
              'How you actually talk to an LLM — messages, caching, sampling, streaming, structured output, tools, multimodal.',
            slug: '/foundations/api',
          },
          items: [
            'foundations/messages',
            'foundations/prompting-craft',
            'foundations/context-window',
            'foundations/prompt-caching',
            'foundations/sampling',
            'foundations/streaming',
            'foundations/structured-output',
            'foundations/tool-use',
            'foundations/function-calling-deep',
            'foundations/mcp',
            'foundations/multimodal-inputs',
          ],
        },
        {
          type: 'category',
          label: 'Retrieval & memory',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Retrieval & memory',
            description:
              'Giving the model knowledge it doesn\'t have — chunking, hybrid search, rerankers, RAG, and memory patterns.',
            slug: '/foundations/retrieval',
          },
          items: [
            'foundations/vector-search',
            'foundations/hybrid-search',
            'foundations/chunking-strategies',
            'foundations/reranking',
            'foundations/rag-basics',
            'foundations/memory',
          ],
        },
        {
          type: 'category',
          label: 'Agents',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Agents',
            description:
              'Letting the model take actions in a loop — what an agent is, planning and reflection, and when multi-agent makes sense.',
            slug: '/foundations/agents',
          },
          items: [
            'foundations/agent-loop',
            'foundations/planning-and-reflection',
            'foundations/multi-agent',
            'foundations/context-engineering',
            'foundations/computer-use',
          ],
        },
        'foundations/foundations-checkpoint',
        'foundations/math-primer',
      ],
    },

    // Chapter 2 — Roadmap (autogen picks up the 4 part subdirectories)
    {
      type: 'category',
      label: '2. Roadmap',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'roadmap/roadmap-overview'},
      items: [{type: 'autogenerated', dirName: '02-roadmap'}],
    },

    // ─────────────────────────────────────────────────────────────
    // Part B · Building & shipping — the process and the tools
    // ─────────────────────────────────────────────────────────────

    // Chapter 3 — Lifecycle
    {
      type: 'category',
      label: '3. Lifecycle',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'lifecycle/ai-project-lifecycle'},
      items: [{type: 'autogenerated', dirName: '03-lifecycle'}],
    },

    // Chapter 4 — Tech Stack, grouped into 6 sub-categories + checkpoint
    {
      type: 'category',
      label: '4. Tech Stack',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'stack/tech-stack-decoded'},
      items: [
        {
          type: 'category',
          label: 'Models',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Models',
            description:
              'Foundation model providers, open-source models, inference servers, and embedding models.',
            slug: '/stack/models',
          },
          items: [
            'stack/closed-providers',
            'stack/open-models',
            'stack/inference-servers',
            'stack/embedding-models',
          ],
        },
        {
          type: 'category',
          label: 'Frameworks & SDKs',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Frameworks & SDKs',
            description:
              'LLM SDKs, prompt management, RAG frameworks, agent frameworks.',
            slug: '/stack/frameworks',
          },
          items: [
            'stack/llm-sdks',
            'stack/prompt-management',
            'stack/prompt-optimization',
            'stack/rag-frameworks',
            'stack/agent-frameworks',
          ],
        },
        {
          type: 'category',
          label: 'Data & retrieval',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Data & retrieval',
            description:
              'Vector databases, document parsing, and synthetic data generation.',
            slug: '/stack/data',
          },
          items: [
            'stack/vector-databases',
            'stack/document-parsing',
            'stack/synthetic-data-tools',
          ],
        },
        {
          type: 'category',
          label: 'Evals & observability',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Evals & observability',
            description:
              'How you measure and monitor LLM systems in development and production.',
            slug: '/stack/evals',
          },
          items: ['stack/eval-tools', 'stack/observability-tools'],
        },
        {
          type: 'category',
          label: 'Infra & ops',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Infra & ops',
            description:
              'Gateways, orchestration, agent runtimes, batch inference, voice infra, and fine-tuning platforms.',
            slug: '/stack/infra',
          },
          items: [
            'stack/ai-gateways',
            'stack/orchestration',
            'stack/agent-runtimes',
            'stack/batch-inference',
            'stack/voice-infra',
            'stack/realtime-voice-engineering',
            'stack/fine-tuning-platforms',
          ],
        },
        'stack/stack-checkpoint',
      ],
    },

    // ─────────────────────────────────────────────────────────────
    // Part C · Core disciplines — measure quality, keep it safe
    // ─────────────────────────────────────────────────────────────
    {
      type: 'category',
      label: '5. Evaluation & Measurement',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'evaluation/evaluation-overview'},
      items: [{type: 'autogenerated', dirName: '13-evaluation'}],
    },
    {
      type: 'category',
      label: '6. Responsible & Safe AI',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'safety/safety-overview'},
      items: [{type: 'autogenerated', dirName: '14-safety'}],
    },

    // ─────────────────────────────────────────────────────────────
    // Part D · Specializations — change the model, go beyond text
    // ─────────────────────────────────────────────────────────────
    {
      type: 'category',
      label: '7. Fine-tuning & Customization',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'fine-tuning/fine-tuning-overview'},
      items: [{type: 'autogenerated', dirName: '15-fine-tuning'}],
    },
    {
      type: 'category',
      label: '8. Multimodal & Voice AI',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'multimodal/multimodal-overview'},
      items: [{type: 'autogenerated', dirName: '16-multimodal'}],
    },

    // ─────────────────────────────────────────────────────────────
    // Part E · Workflows by scale — solo, startup, enterprise, compared
    // ─────────────────────────────────────────────────────────────
    {
      type: 'category',
      label: '9. Solo / Indie',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'solo/indie-ai-workflow'},
      items: [{type: 'autogenerated', dirName: '05-solo'}],
    },
    {
      type: 'category',
      label: '10. Startup AI Team',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'startup/startup-ai-workflow'},
      items: [{type: 'autogenerated', dirName: '06-startup'}],
    },
    {
      type: 'category',
      label: '11. Enterprise AI',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'enterprise/enterprise-ai-workflow'},
      items: [{type: 'autogenerated', dirName: '07-enterprise'}],
    },
    {
      type: 'category',
      label: '12. Comparison',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'comparison/comparison'},
      items: [{type: 'autogenerated', dirName: '08-comparison'}],
    },
    // ─────────────────────────────────────────────────────────────
    // Part F · Judgment & patterns — how to decide, what recurs
    // ─────────────────────────────────────────────────────────────
    {
      type: 'category',
      label: '13. Decisions',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'decisions/decision-frameworks'},
      items: [{type: 'autogenerated', dirName: '09-decisions'}],
    },
    {
      type: 'category',
      label: '14. Production Patterns',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'patterns/production-patterns'},
      items: [{type: 'autogenerated', dirName: '10-patterns'}],
    },
    // ─────────────────────────────────────────────────────────────
    // Part G · Career & reference — grow, study shipped systems, look up
    // ─────────────────────────────────────────────────────────────
    {
      type: 'category',
      label: '15. Career',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'career/career-path'},
      items: [{type: 'autogenerated', dirName: '11-career'}],
    },

    // Chapter 16 — Case Studies (eight shipped 2026 AI architectures)
    {
      type: 'category',
      label: '16. Case Studies',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'case-studies/case-studies-overview'},
      items: [{type: 'autogenerated', dirName: '12-case-studies'}],
    },

    // Chapter 17 — Cutting Edge (optional post-curriculum look ahead)
    {
      type: 'category',
      label: '17. Cutting Edge',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'cutting-edge/cutting-edge-overview'},
      items: [{type: 'autogenerated', dirName: '17-cutting-edge'}],
    },

    // Final capstone — whole-guide assessment ("final boss")
    'capstone',

    // Chapter 18 — Glossary
    'glossary',
  ],
};

export default sidebars;
